version: '3'

services:


  ticket-price:
    image: ticket-price
    network_mode: host
    container_name: ticket-price
    ports:
      - "8081:8081"
    restart: always

  ticket-price-db:
    image: postgres
    network_mode: host
    container_name: ticket-price-db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
      - "DEFAULT_ENCODING=UTF8"
      - "POSTGRES_DB=ticket-price-db"