version: '3'

services:


  ticket-price:
    build: ./
    network_mode: host
    ports:
      - "8081:8081"
    environment:
      - "ticket-price-db=ticket-price-db"
    restart: always

  ticket-price-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
      - "DEFAULT_ENCODING=UTF8"
      - "POSTGRES_DB=ticket-price-db"